# 检查gitlab-runner用户是否有docker执行权限
before_script:
  - docker ps
  
# maven编译打包 and docker run
stages:
    - package
    - run

#cache:
#  paths:
#    - /root/.m2/repository

# 默认运行镜像

variables:

    stms: 172.16.3.20:5000/tomcat:latest

makejava:
    image: 172.16.3.20:5000/maven:3.5.4-jdk-8
    stage: package
    tags:
      - git.shell
    script:
      - pwd
    #  - mvn clean
      - mvn clean package -Dmaven.test.skip=true
      - pwd
      - rm -rf /mnt/code/stms/*
      - cp -r /home/gitlab-runner/builds/9130b5f0/0/szer0/stms/target/stms /mnt/code/stms/
      - du -h --max-depth=1 /mnt/code/stms/
    artifacts:
      name:  "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      paths:
        - stms/*
      expire_in: 1 day
docker-build:
    stage: run
    tags:
      - git.shell
    script:
      - docker stop $(docker ps -a |grep tomcat | awk '{print $1}')
      - docker rm $(docker ps --all -q -f status=exited)
      - docker run -d -p 81:8080 -v /mnt/code/stms/stms/:/usr/local/tomcat/webapps/ROOT/ $stms
